version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "9090:9090"  # Add gRPC port
    environment:
      - APP_NAME=Tack-Ticket
      # Database
      - DB_DRIVER=com.mysql.cj.jdbc.Driver
      - DB_URL=jdbc:mysql://mysql:3306/projectt?useSSL=false&allowPublicKeyRetrieval=true
      - DB_USERNAME=root
      - DB_PASSWORD=root
      # JPA
      - JPA_DIALECT=org.hibernate.dialect.MySQLDialect
      - JPA_DDL_AUTO=update
      # Kafka
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CONSUMER_GROUP_ID=projectt-group
      - KAFKA_CONSUMER_AUTO_OFFSET_RESET=earliest
      # Security
      - JWT_SECRET=your-jwt-secret-key-should-be-very-long-and-secure
      - GOOGLE_CLIENT_ID=your-google-client-id
      # Mail
      - MAIL_USERNAME=your-email@gmail.com
      - MAIL_PASSWORD=your-email-app-password
      - MAIL_SENDER_NAME=ProjectT
      # gRPC
      - GRPC_OCCA_HOST=0.0.0.0  # Changed from localhost
      - GRPC_OCCA_PORT=9090
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=projectt
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  mysql_data: