spring:
  application:
    name: ${APP_NAME:Tack Ticket API}

  # Configure timezone for the application
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: yyyy-MM-dd HH:mm:ss

  # Configure JVM timezone
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
    database-platform: ${JPA_DIALECT:org.hibernate.dialect.MySQLDialect}
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:ticket-service}
      auto-offset-reset: ${KAFKA_CONSUMER_AUTO_OFFSET_RESET:earliest}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

      
app:
  jwtSecret: ${JWT_SECRET}
  googleClientId: ${GOOGLE_CLIENT_ID}
  googleClientSecret: ${GOOGLE_CLIENT_SECRET}
  geminiApiKey: ${GEMINI_API_KEY}
  sepayApiKey: ${SEPAY_API_KEY}
  sepayUrl: ${SEPAY_URL}
  purchaseReal: ${PURCHASE_REAL:false}
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}

  mail:
    username: ${MAIL_USERNAME:Tack Ticket}
    password: ${MAIL_PASSWORD}
    sender-name: ${MAIL_SENDER_NAME}

# Google OAuth configuration
google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8080/v1/auth/google/callback}
  
  website:
    url: ${WEBSITE_URL:https://tackticket.com}

grpc:
  # Cổng mặc định cho gRPC server
  server:
    port: 9090
  
  # Cấu hình cho client
  client:
    occa-service:
      address: static://${GRPC_OCCA_HOST:localhost}:${GRPC_OCCA_PORT:9090}
      negotiationType: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true
    user-service:
      address: static://${GRPC_AUTH_HOST:localhost}:${GRPC_AUTH_PORT:9090}
      negotiationType: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true
    ticket-service:
      address: static://${GRPC_TICKET_HOST:localhost}:${GRPC_TICKET_PORT:9090}
      negotiationType: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true