import { OrganizerOccaUnit } from '../internal-types/organize.type';
import { format, addDays, subDays } from 'date-fns';

const today = new Date();

export const organizeMockData = {
  upcoming: [
    {
      id: "org-1",
      title: "Workshop Làm Gốm Sứddddddddddddddddddddddddddddddddddđ",
      date: format(addDays(today, 14), "yyyy-MM-dd"),
      location: "Gallery G63, Quận 1, TP.HCM",
      status: "active",
      ticketsSold: 25,
      ticketsTotal: 50,
      image: "https://i.pinimg.com/564x/87/23/6b/87236b01fa6c084085edb0612396d62d.jpg",
    },
    {
      id: "org-2",
      title: "Âm Nhạc Đương Đại: Giao Thoa Văn Hóa",
      date: format(addDays(today, 30), "yyyy-MM-dd"),
      location: "Nhà hát Hòa Bình, Quận 10, TP.HCM",
      status: "active",
      ticketsSold: 120,
      ticketsTotal: 500,
      image: "https://static.toiimg.com/thumb/msid-115801253,width-1070,height-580,imgsize-140568,resizemode-75,overlay-toi_sw,pt-32,y_pad-40/photo.jpg",
    },
    {
      id: "org-5",
      title: "Triển Lãm Nghệ Thuật Số",
      date: format(addDays(today, 21), "yyyy-MM-dd"),
      location: "VCCA, Hà Nội",
      status: "active",
      ticketsSold: 75,
      ticketsTotal: 150,
      image: "https://i.pinimg.com/564x/4e/b7/a5/4eb7a5dbd2c1949e9cd2251ce0748e69.jpg",
    },
    {
      id: "org-6",
      title: "Hội Chợ Ẩm Thực Đường Phố",
      date: format(addDays(today, 7), "yyyy-MM-dd"),
      location: "Công viên 23/9, TP.HCM",
      status: "active",
      ticketsSold: 430,
      ticketsTotal: 600,
      image: "https://i.pinimg.com/564x/e0/93/ea/e093ea5f00sldjf29d8a9ac94sdlf2.jpg",
    },
  ] as OrganizerOccaUnit[],
  
  past: [
    {
      id: "org-3",
      title: "Triển Lãm Nhiếp Ảnh: Con Người Việt Nam",
      date: format(subDays(today, 45), "yyyy-MM-dd"),
      location: "Bảo tàng Mỹ thuật Việt Nam, Hà Nội",
      status: "completed",
      ticketsSold: 350,
      ticketsTotal: 350,
      image: "https://i.pinimg.com/564x/28/a5/af/28a5af8c9979a4588362131a417ab1d9.jpg",
    },
    {
      id: "org-7",
      title: "Festival Âm Nhạc Mùa Hè",
      date: format(subDays(today, 60), "yyyy-MM-dd"),
      location: "Bãi biển Nha Trang, Khánh Hòa",
      status: "completed",
      ticketsSold: 1200,
      ticketsTotal: 1500,
      image: "https://i.pinimg.com/564x/8f/e7/ac/8fe7ac9d8c62b5f6c34ec30c68a7b4fc.jpg",
    },
    {
      id: "org-8",
      title: "Hội Nghị Công Nghệ 4.0",
      date: format(subDays(today, 15), "yyyy-MM-dd"),
      location: "Trung tâm Hội nghị Quốc gia, Hà Nội",
      status: "completed",
      ticketsSold: 580,
      ticketsTotal: 600,
      image: "https://i.pinimg.com/564x/78/9e/7a/789e7a7dc9bd6eb2b90d0abb14b679dd.jpg",
    },
  ] as OrganizerOccaUnit[],
  
  draft: [
    {
      id: "org-4",
      title: "Hội Thảo Khởi Nghiệp Xanh",
      date: format(addDays(today, 60), "yyyy-MM-dd"),
      location: "Innovation Hub, Đà Nẵng",
      status: "draft",
      ticketsSold: 0,
      ticketsTotal: 200,
      image: "",
    },
    {
      id: "org-9",
      title: "Lớp Học Nấu Ăn Chay",
      date: format(addDays(today, 45), "yyyy-MM-dd"),
      location: "Culinary Arts Center, TP.HCM",
      status: "draft",
      ticketsSold: 0,
      ticketsTotal: 30,
      image: "",
    },
    {
      id: "org-10",
      title: "Workshop Kỹ Năng Thuyết Trình",
      date: format(addDays(today, 90), "yyyy-MM-dd"),
      location: "WeWork Office, TP.HCM",
      status: "draft",
      ticketsSold: 0,
      ticketsTotal: 50,
      image: "",
    },
  ] as OrganizerOccaUnit[],
};
